build:
	g++ main.cpp custom_func.cpp -o tema1 -lpthread \
		-Wall -Wextra -Wconversion -Wno-sign-conversion \
		-Wdouble-promotion -Wno-unused-parameter \
		-Wno-unused-function -g -O0

clean:
		rm tema1