# Nenciu George-Robert 333CC

build:
	flex tema.l
	g++ lex.yy.c -o tema

clean:
	rm lex.yy.c tema

run:
	./tema automat1.txt automat2.txt automat3.txt automat4.txt gramatica1.txt gramatica2.txt gramatica3.txt gramatica4.txt